### ISSUE TITLE
请教：新增页面路由设置

### ISSUE THREAD

**Issue by askie** [JerryMissTom/HW-basic#2]
UserInfoPage 和 EchartsPage  请教这两个页面没有再app.module.ts里面声明，但是如何能够路由的？
新增页面不知道如何按照你这种方法进行设置。

**Comment by askie** [comment]
知道问题了，ionic g page 后，需要重启才行

**Comment by JerryMissTom** [comment]
@askie 这两个页面应该是懒加载界面，不需要在app.module.ts中声明的。具体你可以看我之前写的另一篇[界面跳转](https://juejin.im/post/5adf096551882567382f3ca2)
